language: node_js
node_js:
- node
jobs:
  include:
  - stage: Test
    script: npm test
  - stage: Build & Deploy
    name: Build OS X
    if: tag IS present && branch = master
    os: osx
    script: npm run compile && npm run release:osx
  - name: Build OS X Insider
    if: tag IS present && branch != master
    os: osx
    script: npm run compile && npm run prerelease:osx
  - name: Build Linux
    if: tag IS present && branch = master
    os: linux
    script: npm run compile && npm run release:linux
  - name: Build Linux Insider
    if: tag IS present && branch != master
    os: linux
    script: npm run compile && npm run prerelease:linux
  - name: Build Windows
    if: tag IS present && branch = master
    os: win
    script: npm run compile && npm run release:win
  - name: Build Windows Insider
    if: tag IS present && branch != master
    os: win
    script: npm run compile && npm run prerelease:win
