language: node_js

node_js:
- node

sudo: required

stages:
  - Test
  - name: Build OSX
    if: tag ~= /^v\d+\.\d+\.\d+$/
    # if: branch = master
  - name: Build Linux
    if: tag ~= /^v\d+\.\d+\.\d+$/
    # if: branch = master
  - name: Build Windows
    if: tag ~= /^v\d+\.\d+\.\d+$/
    # if: branch = master
  - name: Build OSX Insider
    if: tag ~= /^v\d+\.\d+\.\d+\-\w+\.\d+$/
    # if: branch = develop
  - name: Build Linux Insider
    if: tag ~= /^v\d+\.\d+\.\d+\-\w+\.\d+$/
    # if: branch = develop
  - name: Build Windows Insider
    if: tag ~= /^v\d+\.\d+\.\d+\-\w+\.\d+$/
    # if: branch = develop

jobs:
  include:
  # Test stage
  - stage: Test
    install:
      - npm ci
    script:
      - npm test

  # Normal build stage
  - stage: Build Windows
    os: windows
    install:
      - ./.travis/InstallWin.bat
    script:
      - npm run compile
      - npm run release:win

  - stage: Build Linux
    os: linux
    install:
      - sh ./.travis/InstallLinux.sh
    script:
      - npm run compile
      - npm run release:linux

  - stage: Build OSX
    os: osx
    install:
      - sh ./.travis/InstallMac.sh
    script:
      - npm run compile
      - npm run release:osx

  # Insider build stage
  - stage: Build Windows Insider
    os: windows
    install:
      - ./.travis/InstallWin.bat
    script:
      - npm run compile
      - npm run prerelease:win

  - stage: Build Linux Insider
    os: linux
    install:
      - sh ./.travis/InstallLinux.sh
    script:
      - npm run compile
      - npm run prerelease:linux

  - stage: Build OSX Insider
    os: osx
    install:
      - sh ./.travis/InstallMac.sh
    script:
      - npm run compile
      - npm run prerelease:osx
