language: node_js

node_js:
- node

sudo: required

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $ACCESS_TOKEN" > ~/.netrc
  - git submodule update --init --recursive

stages:
  - Test
  - name: Build
    if: tag ~= /^v\d+\.\d+\.\d+$/
    # if: branch = master
  - name: Build Insider
    if: tag ~= /^v\d+\.\d+\.\d+\-\w+\.\d+$/
    # if: branch = develop

jobs:
  include:
  # Test stage
  - stage: Test
    os: linux
    script:
      - npm run re:build
      - npm test
      - npm run lint

  # Normal build stage
  - stage: Build
    name: Build Windows
    os: windows
    script:
      - npm run re:build
      - npm run ts:build
      - npm run stable:win

  - name: Build Linux
    os: linux
    script:
      - npm run re:build
      - npm run ts:build
      - npm run stable:linux

  - name: Build OSX
    os: osx
    osx_image: xcode11.2
    script:
      - npm run re:build
      - npm run ts:build
      - npm run stable:osx

  # Insider build stage
  - stage: Build Insider
    name: Build Windows Insider
    os: windows
    script:
      - npm run re:build
      - npm run ts:build
      - npm run insider:win

  - name: Build Linux Insider
    os: linux
    script:
      - npm run re:build
      - npm run ts:build
      - npm run insider:linux

  - name: Build OSX Insider
    os: osx
    osx_image: xcode11.2
    script:
      - npm run re:build
      - npm run ts:build
      - npm run insider:osx
