language: generic

before-install:
  - echo before install

install:
  - sudo apt-get update
  - sudo apt-get install -y curl python3
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
  - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion'
  - nvm install node
  - node --version
  - npm --version
  - npm i
  - python3 prepareTables.py

stages:
  - test
  - name: build
    if: branch = master
  - name: buildInsider
    if: branch = develop

jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: build
    script:
    - npm run compile
    - npm run release:win
    - npm run release:linux
    - npm run release:osx
    - echo Collecting artifacts
  - stage: buildInsider
    script:
    - npm run compile
    - npm run prerelease:win
    - npm run prerelease:linux
    - npm run prerelease:osx
    - echo Collecting artifacts