name: Bug report
description: Create a report to help improve Optolith
labels:
  - Bug
body:
  - type: checkboxes
    id: agreements
    attributes:
      label: Please confirm the following
      options:
        - label: I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating systems have you used? You may select more than one.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which Optolith version have you used?
      placeholder: 1.1.0, 1.3.0-alpha.5, …
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
