name: Build Prerelease

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+
    branches:
    - develop

jobs:
  build:
    name: Build prerelease on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        include:
        - os: ubuntu-latest
          command: prerelease:linux
        - os: windows-latest
          command: prerelease:win
        - os: macOS-latest
          command: prerelease:mac
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Node.js dependencies
      run: npm ci
    - name: Build ReasonML files
      run: npm run re:build
    - name: Build TypeScript files
      run: npm run ts:build
    - name: Build
      run: npm run ${{ matrix.command }}
