name: TS/RE Tests

on:
  push:
    branches: 
    - develop
  pull_request:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: sh ./.travis/InstallLinux.sh
    - run: npm ci
    - run: npm run yaml:decrypt
      env:
        OPTOLITH_KEY: ${{ secrets.OPTOLITH_KEY }}
    - run: npm run ci:copyschemes
    - run: npm run re:build
    - run: npm run ts:build
    - run: npm test
      env:
        CI: true
